# Site settings
title: Nick Randall
header-img: img/home-bg.jpg
email: nicksrandall@gmail.com
description: "Web Tech thoughts by Nick Randall!"
baseurl: ""
url: "http://nicksrandall.github.io"
twitter_username: nicksrandall
github_username:  nicksrandall
facebook_username:  nick.randall

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
